In [6]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from bs4 import BeautifulSoup
import requests

In [7]:
link_cloud_lab_processor = "https://docs.cloudlab.us/hardware.html"
reqs = requests.get(link_cloud_lab_processor)
soup = BeautifulSoup(reqs.text, 'html.parser')

In [8]:
# Find all the tables with class="boxed"
all_tables = soup.find_all('table', class_='boxed')

In [10]:
all_tables[0]

<table cellpadding="0" cellspacing="0" class="boxed"><tr><td><p><span style="font-weight: bold">m400</span></p></td><td><p><span class="hspace">   </span></p></td><td><p>270 nodes (64-bit ARM)</p></td></tr><tr><td><p>CPU</p></td><td><p><span class="hspace">   </span></p></td><td><p>Eight 64-bit ARMv8 (Atlas/A57) cores at 2.4 GHz (APM X-GENE)</p></td></tr><tr><td><p>RAM</p></td><td><p><span class="hspace">   </span></p></td><td><p>64GB ECC Memory (8x 8 GB DDR3-1600 SO-DIMMs)</p></td></tr><tr><td><p>Disk</p></td><td><p><span class="hspace">   </span></p></td><td><p>120 GB of flash (SATA3 / M.2, Micron M500)</p></td></tr><tr><td><p>NIC</p></td><td><p><span class="hspace">   </span></p></td><td><p>Dual-port Mellanox ConnectX-3 10 GB NIC (PCIe v3.0, 8 lanes (one port available for experiment use)</p></td></tr></table>

In [23]:
df = pd.read_html(str(all_tables))

In [17]:
len(df)

34

In [28]:
df_cloudlab_processor = pd.DataFrame()

In [29]:
# Iterate over each table and convert it to a DataFrame
for table in all_tables:
    # Convert the table to a DataFrame
    df = pd.read_html(str(table))[0]
    
    # Rename the 'A' column to 'X'
  
    df_cloudlab_processor = pd.concat([df_cloudlab_processor, df], ignore_index=False)

In [30]:
df_cloudlab_processor

       0   1                                                  2
0   m400 NaN                             270 nodes (64-bit ARM)
1    CPU NaN  Eight 64-bit ARMv8 (Atlas/A57) cores at 2.4 GH...
2    RAM NaN       64GB ECC Memory (8x 8 GB DDR3-1600 SO-DIMMs)
3   Disk NaN         120 GB of flash (SATA3 / M.2, Micron M500)
4    NIC NaN  Dual-port Mellanox ConnectX-3 10 GB NIC (PCIe ...
..   ...  ..                                                ...
0   m400 NaN                              45 nodes (64-bit ARM)
1    CPU NaN  Eight 64-bit ARMv8 (Atlas/A57) cores at 2.4 GH...
2    RAM NaN       64GB ECC Memory (8x 8 GB DDR3-1600 SO-DIMMs)
3   Disk NaN         120 GB of flash (SATA3 / M.2, Micron M500)
4    NIC NaN  Dual-port Mellanox ConnectX-3 10 GB NIC (PCIe ...

[217 rows x 3 columns]

In [33]:
df_cloudlab_processor.columns

Int64Index([0, 1, 2], dtype='int64')

In [35]:
df_cloudlab_processor = df_cloudlab_processor.drop(columns=[1])

In [36]:
df_cloudlab_processor

       0                                                  2
0   m400                             270 nodes (64-bit ARM)
1    CPU  Eight 64-bit ARMv8 (Atlas/A57) cores at 2.4 GH...
2    RAM       64GB ECC Memory (8x 8 GB DDR3-1600 SO-DIMMs)
3   Disk         120 GB of flash (SATA3 / M.2, Micron M500)
4    NIC  Dual-port Mellanox ConnectX-3 10 GB NIC (PCIe ...
..   ...                                                ...
0   m400                              45 nodes (64-bit ARM)
1    CPU  Eight 64-bit ARMv8 (Atlas/A57) cores at 2.4 GH...
2    RAM       64GB ECC Memory (8x 8 GB DDR3-1600 SO-DIMMs)
3   Disk         120 GB of flash (SATA3 / M.2, Micron M500)
4    NIC  Dual-port Mellanox ConnectX-3 10 GB NIC (PCIe ...

[217 rows x 2 columns]

In [39]:
df_cloudlab_processor = df_cloudlab_processor.rename(columns={0: "resource", 2: "description"})

In [40]:
df_cloudlab_processor

   resource                                        description
0      m400                             270 nodes (64-bit ARM)
1       CPU  Eight 64-bit ARMv8 (Atlas/A57) cores at 2.4 GH...
2       RAM       64GB ECC Memory (8x 8 GB DDR3-1600 SO-DIMMs)
3      Disk         120 GB of flash (SATA3 / M.2, Micron M500)
4       NIC  Dual-port Mellanox ConnectX-3 10 GB NIC (PCIe ...
..      ...                                                ...
0      m400                              45 nodes (64-bit ARM)
1       CPU  Eight 64-bit ARMv8 (Atlas/A57) cores at 2.4 GH...
2       RAM       64GB ECC Memory (8x 8 GB DDR3-1600 SO-DIMMs)
3      Disk         120 GB of flash (SATA3 / M.2, Micron M500)
4       NIC  Dual-port Mellanox ConnectX-3 10 GB NIC (PCIe ...

[217 rows x 2 columns]

In [42]:
df_cloudlab_processor_intel = df_cloudlab_processor[
    df_cloudlab_processor["description"].str.contains("Intel", regex=False, case=False)]

In [43]:
df_cloudlab_processor_intel

   resource                                        description
0      m510                           270 nodes (Intel Xeon-D)
1       CPU            Eight-core Intel Xeon D-1548 at 2.0 GHz
0     xl170       200 nodes (Intel Broadwell, 10 core, 1 disk)
1       CPU                Ten-core Intel E5-2640v4 at 2.4 GHz
3      Disk                  Intel DC S3520 480 GB 6G SATA SSD
..      ...                                                ...
0      r650  32 nodes (Intel Ice Lake, 72 core, 256GB RAM, ...
1       CPU    Two 36-core Intel Xeon Platinum 8360Y at 2.4GHz
5       NIC    1 x Intel X520 PCIe Dual port 10Gb Ethernet NIC
4       NIC                1GbE Quad port embedded NIC (Intel)
4       NIC                1GbE Quad port embedded NIC (Intel)

[61 rows x 2 columns]

In [44]:
df_cloudlab_processor_intel = df_cloudlab_processor_intel[df_cloudlab_processor_intel["resource"]=="CPU"]

In [45]:
df_cloudlab_processor_intel

  resource                                        description
1      CPU            Eight-core Intel Xeon D-1548 at 2.0 GHz
1      CPU                Ten-core Intel E5-2640v4 at 2.4 GHz
1      CPU            16-core Intel Xeon Gold 6326 at 2.90GHz
1      CPU  Two Intel E5-2630 v3 8-core CPUs at 2.40 GHz (...
1      CPU  Two Intel E5-2630 v3 8-core CPUs at 2.40 GHz (...
1      CPU  Two Intel E5-2660 v3 10-core CPUs at 2.60 GHz ...
1      CPU  Two Intel E5-2660 v3 10-core CPUs at 2.60 GHz ...
1      CPU  Two Intel Xeon Silver 4114 10-core CPUs at 2.2...
1      CPU  Two Intel Xeon Silver 4114 10-core CPUs at 2.2...
1      CPU     Two Intel Xeon E5-2667 8-core CPUs at 3.20 GHz
1      CPU  One Intel Xeon Silver 4314 16-core CPU at 2.40...
1      CPU  Two Intel Xeon Silver 4314 16-core CPU at 2.40...
1      CPU  Two Intel E5-2660 v2 10-core CPUs at 2.20 GHz ...
1      CPU  Two Intel E5-2660 v2 10-core CPUs at 2.20 GHz ...
1      CPU  Two Intel E5-2683 v3 14-core CPUs at 2.00 GHz ...
1      CPU  Two Intel E5-2680 v3 12-core processors at 2.5...
1      CPU  Two Intel E5-2620 v3 6-core CPUs at 2.40 GHz (...
1      CPU  Two Sixteen-core Intel Xeon Gold 6142 CPUs at ...
1      CPU    Two 36-core Intel Xeon Platinum 8360Y at 2.4GHz

In [52]:
df_cloudlab_processor_intel.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19 entries, 1 to 1
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   resource     19 non-null     object
 1   description  19 non-null     object
dtypes: object(2)
memory usage: 456.0+ bytes

<font color='red'><h1> Il Faut te Reposer </h1></font>